#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18408
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: Android.Runtime.ResourceDesignerAttribute("WEBAPP.Resource", IsApplication=true)]

namespace WEBAPP
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues ();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f040008
			public const int Silver = 2130968584;
			
			// aapt resource value: 0x7f04000f
			public const int TextColorBlack = 2130968591;
			
			// aapt resource value: 0x7f040010
			public const int TextColorBlue = 2130968592;
			
			// aapt resource value: 0x7f040016
			public const int TextColorBlue1 = 2130968598;
			
			// aapt resource value: 0x7f040011
			public const int TextColorGray = 2130968593;
			
			// aapt resource value: 0x7f040013
			public const int TextColorGreen = 2130968595;
			
			// aapt resource value: 0x7f040017
			public const int TextColorGreen1 = 2130968599;
			
			// aapt resource value: 0x7f040012
			public const int TextColorRed = 2130968594;
			
			// aapt resource value: 0x7f040014
			public const int TextColorRed1 = 2130968596;
			
			// aapt resource value: 0x7f040015
			public const int TextColorYellow1 = 2130968597;
			
			// aapt resource value: 0x7f040023
			public const int background_color = 2130968611;
			
			// aapt resource value: 0x7f040002
			public const int black = 2130968578;
			
			// aapt resource value: 0x7f040003
			public const int blue = 2130968579;
			
			// aapt resource value: 0x7f040000
			public const int border_line = 2130968576;
			
			// aapt resource value: 0x7f04001e
			public const int button_selected = 2130968606;
			
			// aapt resource value: 0x7f04001d
			public const int button_unselected = 2130968605;
			
			// aapt resource value: 0x7f040005
			public const int gray = 2130968581;
			
			// aapt resource value: 0x7f04000d
			public const int gray_bold = 2130968589;
			
			// aapt resource value: 0x7f04001f
			public const int info_panel_bg = 2130968607;
			
			// aapt resource value: 0x7f04000e
			public const int movie_name = 2130968590;
			
			// aapt resource value: 0x7f04000a
			public const int noread = 2130968586;
			
			// aapt resource value: 0x7f040004
			public const int orangered = 2130968580;
			
			// aapt resource value: 0x7f040009
			public const int readed = 2130968585;
			
			// aapt resource value: 0x7f040007
			public const int red = 2130968583;
			
			// aapt resource value: 0x7f04001c
			public const int title_bg = 2130968604;
			
			// aapt resource value: 0x7f040020
			public const int traffic_bg = 2130968608;
			
			// aapt resource value: 0x7f040022
			public const int traffic_data = 2130968610;
			
			// aapt resource value: 0x7f040021
			public const int traffic_txt = 2130968609;
			
			// aapt resource value: 0x7f04000c
			public const int transparent = 2130968588;
			
			// aapt resource value: 0x7f04000b
			public const int transparent01 = 2130968587;
			
			// aapt resource value: 0x7f040001
			public const int white = 2130968577;
			
			// aapt resource value: 0x7f04001b
			public const int window_bg = 2130968603;
			
			// aapt resource value: 0x7f040006
			public const int yello = 2130968582;
			
			// aapt resource value: 0x7f04001a
			public const int zzblack = 2130968602;
			
			// aapt resource value: 0x7f040018
			public const int zzblue = 2130968600;
			
			// aapt resource value: 0x7f040019
			public const int zzyellow = 2130968601;
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f060000
			public const int webView = 2131099648;
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Main = 2130903040;
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050001
			public const int ApplicationName = 2131034113;
			
			// aapt resource value: 0x7f050000
			public const int Hello = 2131034112;
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
